[zsh] Add fzf tab source and fix brew wrapper function

diff --git a/private_dot_config/zsh/plugins.zsh.tmpl b/private_dot_config/zsh/plugins.zsh.tmpl
--- a/private_dot_config/zsh/plugins.zsh.tmpl
+++ b/private_dot_config/zsh/plugins.zsh.tmpl
@@ -12,17 +12,27 @@ for p in "${OMZ_PLUGINS[@]}"; do
   plug "$ZDOTDIR/omz/plugins/$p"
 done
 
-# Sketchybar interactivity overloads
-function brew() {
-  output=$(command brew "$@")
-  local exit_status=$?
+# Wrapper function to trigger SketchyBar after specific brew commands
+brew() {
+  local target_cmds=("update" "upgrade" "outdated")
+  local subcommand="$1"
 
-  echo "$output"
+  # Run the actual brew command with all arguments
+  command brew "$@"
+  local exit_code=$?
 
-  if [[ $* =~ "upgrade" ]] || [[ $* =~ "update" ]] || [[ $* =~ "outdated" ]]; then
-    sketchybar --trigger brew_update
+  # Check if the command was one of our targets
+  # and if it finished successfully (exit code 0)
+  if [[ ${target_cmds[(r)$subcommand]} == $subcommand ]] && [[ $exit_code -eq 0 ]]; then
+    
+    # Trigger the event name "brew_update"
+    if command -v sketchybar >/dev/null 2>&1; then
+      sketchybar --trigger brew_update
+    fi
+    
   fi
 
-  return $exit_status
+  # Return the original exit code
+  return $exit_code
 }
 
